### ISSUE TITLE
Is https://trigger.esp8266-server.de/ down?

### ISSUE THREAD

**Issue by tmorse305** [MichaelDworkin/Alexa-doorbell--ESP8266-1#1]
Hi,

I can't access https://trigger.esp8266-server.de/.  Is it down temporarily or have you shut it down?

It's a great tool, thanks for creating it.

Regards,

Tim

**Comment by MichaelDworkin** [comment]
My hosting has planned Maintenance work on the server from June 10 to 12It should work again afterwards

GreetingsMichael

    Am Freitag, 14. Juni 2024 um 00:43:51 MESZ hat tmorse305 ***@***.***> Folgendes geschrieben:  
 
 


Hi,

I can't access https://trigger.esp8266-server.de/. Is it down temporarily or have you shut it down?

It's a great tool, thanks for creating it.

Regards,

Tim

**Comment by tmorse305** [comment]
Thank you for the quick reply and update.
Best Regards,

Tim
